spring:
  # ??????????
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: minio_test

minio:
  server: http://47.92.216.0
  port: 19000
  accessKey: minio
  secretKey: 12345678
  bucket: shoy
  urlprefix: /minio/

server:
  port: 8080

logging:
  config: classpath:lockback.xml